title: Hrafn Docs
description: Documentation and reference material for Hrafn.
theme: minima
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
exclude:
  - docs-pages
  - .pages-src
  - .site
